apiVersion: v1
kind: Service
metadata:
  name: aegisops-service
  labels:
    app: aegisops
spec:
  selector:
    app: aegisops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
